<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.9" tiledversion="1.9.0" name="Solid Blocks" tilewidth="64" tileheight="64" spacing="2" margin="2" tilecount="64" columns="8">
 <image source="SolidBlocks.png" trans="ff00ff" width="530" height="530"/>
 <tile id="0" class="Stone"/>
 <tile id="1" class="Stone"/>
 <tile id="2" class="Stone"/>
 <tile id="3" class="Stone"/>
 <tile id="4" class="Stone"/>
 <tile id="5" class="Stone"/>
 <tile id="6" class="Stone"/>
 <tile id="7" class="Stone"/>
 <tile id="8" class="Stone"/>
 <tile id="9" class="Stone"/>
 <tile id="10" class="Stone"/>
 <tile id="11" class="Stone"/>
 <tile id="12" class="Stone"/>
 <tile id="13" class="Stone"/>
 <tile id="14" class="Stone"/>
 <tile id="15" class="Stone"/>
 <tile id="16" class="Stone"/>
 <tile id="17" class="Stone"/>
 <tile id="18" class="Stone"/>
 <tile id="19" class="Stone"/>
 <tile id="20" class="Stone"/>
 <tile id="21" class="Stone"/>
 <tile id="22" class="Stone"/>
 <tile id="23" class="Stone"/>
 <tile id="24" class="Stone"/>
 <tile id="25" class="Stone"/>
 <tile id="26" class="Stone"/>
 <tile id="27" class="Stone"/>
 <tile id="28" class="Stone"/>
 <tile id="29" class="Stone"/>
 <tile id="30" class="Stone"/>
 <tile id="31" class="Stone"/>
 <tile id="32" class="Stone"/>
 <tile id="33" class="Stone"/>
 <tile id="34" class="Stone"/>
 <tile id="35" class="Stone"/>
 <tile id="36" class="Stone"/>
 <tile id="37" class="Stone"/>
 <tile id="38" class="Stone"/>
 <tile id="39" class="Stone"/>
 <tile id="40" class="Stone"/>
 <tile id="41" class="Stone"/>
 <tile id="42" class="Stone"/>
 <tile id="43" class="Stone"/>
 <tile id="44" class="Stone"/>
 <tile id="45" class="Stone"/>
 <tile id="46" class="Stone"/>
 <tile id="47" class="Stone"/>
 <tile id="48" class="Stone"/>
 <tile id="49" class="Stone"/>
 <tile id="50" class="Stone"/>
 <tile id="51" class="Stone"/>
 <tile id="52" class="Stone"/>
 <tile id="53" class="Stone"/>
 <tile id="54" class="Stone"/>
 <tile id="55" class="Stone"/>
 <tile id="56" class="Stone"/>
 <tile id="57" class="Stone"/>
 <tile id="58" class="Stone"/>
 <tile id="59" class="Stone"/>
 <tile id="60" class="Stone"/>
 <tile id="61" class="Stone"/>
 <tile id="62" class="Stone"/>
 <tile id="63" class="Stone"/>
</tileset>
